version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    networks:
      - net
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

    networks:
      - net

  producer:
    image: producer
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    networks:
      - net

  consumer:
    image: consumer
    ports:
      - "8090:8090"
    depends_on:
      - producer
      - kafka
    networks:
      - net



networks:
  net:
    driver: bridge
